version: '3'
services:
  hello-w:
    image: acrtestlsn.azurecr.io/aci-helloworld:v1
    ports:
        - "8080:80"
    deploy:
      placement:
        constraints:
          - node.labels.ft == www
