version: '3.4'
services:
  whoami0:
    image: emilevauge/whoam
    deploy:
      labels:
        - traefik.port=80
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
