version: '3.4'
services:
  whoami0:
    image: emilevauge/whoami
    deploy:
      labels:
        traefik.docker.network=traefik_default
        traefik.port=80
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
